<a href="https://colab.research.google.com/github/Lohitharepalle/Machine-Learning/blob/main/Data_Preprocessing_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot
df = pd.read_csv('/content/Iris.csv')
array = df.values
X = array[:,0:5]
Y = array[:,5]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.    0.222 0.625 0.068 0.042]
 [0.007 0.167 0.417 0.068 0.042]
 [0.013 0.111 0.5   0.051 0.042]
 [0.02  0.083 0.458 0.085 0.042]
 [0.027 0.194 0.667 0.068 0.042]]


In [ ]:
from sklearn.preprocessing import StandardScaler 
X = array[:,0:5]
Y = array[:,5]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[-1.721 -0.901  1.032 -1.341 -1.313]
 [-1.697 -1.143 -0.125 -1.341 -1.313]
 [-1.674 -1.385  0.338 -1.398 -1.313]
 [-1.651 -1.507  0.106 -1.284 -1.313]
 [-1.628 -1.022  1.263 -1.341 -1.313]]


In [ ]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[0.156 0.794 0.545 0.218 0.031]
 [0.32  0.785 0.48  0.224 0.032]
 [0.457 0.716 0.488 0.198 0.03 ]
 [0.571 0.657 0.443 0.214 0.029]
 [0.62  0.62  0.447 0.174 0.025]]


In [ ]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
import pandas as pd
from sklearn import preprocessing
my_data = {
"Gender" : ['F', 'M', 'M', 'F', 'M', 'F', 'M', 'F' ,'F', 'M'],
"Name" : ['Cindy', 'Carl', 'Johnny', 'Stacey', 'Andy', 'Sara', 'Victor', 'Martha', 'Mindy', 'Max']
}
blk = pd.DataFrame( my_data )
print("Geniune Data Frame: \n")
print( blk )
my_label = preprocessing. LabelEncoder()
blk['Gender']= my_label.fit_transform(blk[ 'Gender' ])
print(blk[ 'Gender' ].unique())
print("Data Frame after Label Encoding: \n")
print( blk )

Geniune Data Frame: 

  Gender    Name
0      F   Cindy
1      M    Carl
2      M  Johnny
3      F  Stacey
4      M    Andy
5      F    Sara
6      M  Victor
7      F  Martha
8      F   Mindy
9      M     Max
[0 1]
Data Frame after Label Encoding: 

   Gender    Name
0       0   Cindy
1       1    Carl
2       1  Johnny
3       0  Stacey
4       1    Andy
5       0    Sara
6       1  Victor
7       0  Martha
8       0   Mindy
9       1     Max


In [ ]:
import numpy as np
import pandas as pd
X=pd.read_csv('/content/diabetes.csv')
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  